#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-worker-template"
main = "src/main.ts"
compatibility_date = "2024-10-30"

# Workers Logs
# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true
